// This file is auto-generated by scripts/update-maxpreps-teams.mjs
// Source: MaxPreps team pages
// Generated at: 2026-04-06T04:06:44.110Z

export const MAXPREPS_TEAMS_GENERATED_AT = "2026-04-06T04:06:44.110Z";

export type MaxprepsTeamData = {
  maxprepsUrl?: string;
  stateRank?: number;
  lastUpdated?: string;
};

export const maxprepsTeamData: Record<string, MaxprepsTeamData> = {
  "riordan": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-francisco/archbishop-riordan-crusaders/football/",
    "stateRank": 10,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "serra": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-mateo/serra-padres/football/",
    "stateRank": 34,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "st-francis": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/mountain-view/st-francis-lancers/football/",
    "stateRank": 66,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "st-ignatius": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-francisco/st-ignatius-wildcats/football/",
    "stateRank": 70,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "mitty": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/archbishop-mitty-monarchs/football/",
    "stateRank": 75,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "valley-christian": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/valley-christian-warriors/football/",
    "stateRank": 150,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "bellarmine": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/bellarmine-college-prep-bells/football/",
    "stateRank": 300,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "sacred-heart": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-francisco/sacred-heart-cathedral-preparatory-fightin-irish/football/",
    "stateRank": 101,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "los-gatos": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/los-gatos/los-gatos-wildcats/football/",
    "stateRank": 45,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "wilcox": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/santa-clara/wilcox-chargers/football/",
    "stateRank": 211,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "palo-alto": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/palo-alto/palo-alto-vikings/football/",
    "stateRank": 691,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "menlo-atherton": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/atherton/menlo-atherton-bears/football/",
    "stateRank": 200,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "christopher": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/gilroy/christopher-cougars/football/",
    "stateRank": 432,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "leigh": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/leigh-longhorns/football/",
    "stateRank": 356,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "leland": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/leland-chargers/football/",
    "stateRank": 738,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "oak-grove": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/oak-grove-eagles/football/",
    "stateRank": 880,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "salinas": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/salinas/salinas-cowboys/football/",
    "stateRank": 136,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "palma": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/salinas/palma-chieftains/football/",
    "stateRank": 87,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "aptos": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/aptos/aptos-mariners/football/",
    "stateRank": 638,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "sacred-heart-prep": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/atherton/sacred-heart-prep-gators/football/",
    "stateRank": 335,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "andrew-hill": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/hill-falcons/football/",
    "stateRank": 1029,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "branham": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/branham-bruins/football/",
    "stateRank": 326,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "del-mar": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/del-mar-dons/football/",
    "stateRank": 904,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "evergreen-valley": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/evergreen-valley-cougars/football/",
    "stateRank": 935,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "gunderson": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/gunderson-grizzlies/football/",
    "stateRank": 599,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "independence": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/independence-76ers/football/",
    "stateRank": 908,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "james-lick": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/james-lick-comets/football/",
    "stateRank": 1021,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "lincoln": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/lincoln-lions/football/",
    "stateRank": 233,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "live-oak": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/morgan-hill/live-oak-acorns/football/",
    "stateRank": 258,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "mt-pleasant": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/mt-pleasant-cardinals/football/",
    "stateRank": 1000,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "overfelt": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/overfelt-royals/football/",
    "stateRank": 668,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "piedmont-hills": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/piedmont-hills-pirates/football/",
    "stateRank": 449,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "pioneer": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/pioneer-mustangs/football/",
    "stateRank": 645,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "prospect": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/saratoga/prospect-panthers/football/",
    "stateRank": 892,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "san-jose": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/san-jose-bulldogs/football/",
    "stateRank": 812,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "santa-teresa": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/santa-teresa-saints/football/",
    "stateRank": 175,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "silver-creek": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/silver-creek-raiders/football/",
    "stateRank": 682,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "sobrato": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/morgan-hill/ann-sobrato-bulldogs/football/",
    "stateRank": 480,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "westmont": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/campbell/westmont-warriors/football/",
    "stateRank": 839,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "willow-glen": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/willow-glen-rams/football/",
    "stateRank": 340,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "yerba-buena": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/yerba-buena-aztec-warriors/football/",
    "stateRank": 854,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "cupertino": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/cupertino/cupertino-pioneers/football/",
    "stateRank": 1014,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "fremont": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/sunnyvale/fremont-firebirds/football/",
    "stateRank": 868,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "gunn": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/palo-alto/gunn-titans/football/",
    "stateRank": 938,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "homestead": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/cupertino/homestead-mustangs/football/",
    "stateRank": 602,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "los-altos": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/los-altos/los-altos-eagles/football/",
    "stateRank": 817,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "lynbrook": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/lynbrook-vikings/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "milpitas": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/milpitas/milpitas-trojans/football/",
    "stateRank": 649,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "monta-vista": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/cupertino/monta-vista-matadors/football/",
    "stateRank": 905,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "mountain-view": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/mountain-view/mountain-view-spartans/football/",
    "stateRank": 586,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "santa-clara": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/santa-clara/santa-clara-bruins/football/",
    "stateRank": 832,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "saratoga": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/saratoga/saratoga-falcons/football/",
    "stateRank": 661,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "aragon": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-mateo/aragon-dons/football/",
    "stateRank": 563,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "capuchino": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-bruno/capuchino-mustangs/football/",
    "stateRank": 667,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "carlmont": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/belmont/carlmont-scots/football/",
    "stateRank": 724,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "el-camino": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/south-san-francisco/el-camino-colts/football/",
    "stateRank": 769,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "half-moon-bay": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/half-moon-bay/half-moon-bay-cougars/football/",
    "stateRank": 350,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "hillsdale": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-mateo/hillsdale-fighting-knights/football/",
    "stateRank": 662,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "jefferson": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/daly-city/jefferson-grizzlies/football/",
    "stateRank": 540,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "mills": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/millbrae/mills-vikings/football/",
    "stateRank": 944,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "oceana": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/pacifica/oceana-sharks/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "san-mateo": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-mateo/san-mateo-bearcats/football/",
    "stateRank": 279,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "sequoia": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/redwood-city/sequoia-ravens/football/",
    "stateRank": 525,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "south-san-francisco": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/south-san-francisco/south-san-francisco-warriors/football/",
    "stateRank": 708,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "terra-nova": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/pacifica/terra-nova-tigers/football/",
    "stateRank": 558,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "westmoor": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/daly-city/westmoor-rams/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "woodside": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/woodside/woodside-wildcats/football/",
    "stateRank": 250,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "burlingame": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/burlingame/burlingame-panthers/football/",
    "stateRank": 404,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "menlo-school": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/atherton/menlo-school-knights/football/",
    "stateRank": 169,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "alisal": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/salinas/alisal-trojans/football/",
    "stateRank": 312,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "anzar": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-juan-bautista/anzar-hawks/football/",
    "stateRank": 80,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "carmel": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/carmel/carmel-padres/football/",
    "stateRank": 383,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "ceiba": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/watsonville/ceiba-college-preparatory-academy-spartans/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "gonzales": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/gonzales/gonzales-spartans/football/",
    "stateRank": 849,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "greenfield": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/greenfield/greenfield-bruins/football/",
    "stateRank": 853,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "hollister": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/hollister/hollister-haybalers/football/",
    "stateRank": 417,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "king-city": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/king-city/king-city-mustangs/football/",
    "stateRank": 369,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "marina": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/marina/marina-mariners/football/",
    "stateRank": 855,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "monterey": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/monterey/monterey-dores/football/",
    "stateRank": 438,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "monte-vista-christian": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/watsonville/monte-vista-christian-mustangs/football/",
    "stateRank": 669,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "north-monterey-county": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/castroville/north-monterey-county-condors/football/",
    "stateRank": 825,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "north-salinas": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/salinas/north-salinas-vikings/football/",
    "stateRank": 323,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "pacific-grove": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/pacific-grove/pacific-grove-breakers/football/",
    "stateRank": 694,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "pajaro-valley": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/watsonville/pajaro-valley-grizzlies/football/",
    "stateRank": 795,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "rancho-san-juan": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/salinas/rancho-san-juan-trailblazers/football/",
    "stateRank": 979,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "seaside": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/seaside/seaside-spartans/football/",
    "stateRank": 852,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "soledad": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/soledad/soledad-aztecs/football/",
    "stateRank": 573,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "watsonville": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/watsonville/watsonville-wildcatz/football/",
    "stateRank": 685,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "harbor": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/santa-cruz/harbor-pirates/football/",
    "stateRank": 990,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "san-lorenzo-valley": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/felton/san-lorenzo-valley-cougars/football/",
    "stateRank": 522,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "santa-cruz": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/santa-cruz/santa-cruz-cardinals/football/",
    "stateRank": 634,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "scotts-valley": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/scotts-valley/scotts-valley-falcons/football/",
    "stateRank": 418,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "soquel": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/soquel/soquel-knights/football/",
    "stateRank": 94,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "harker": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/harker-eagles/football/",
    "stateRank": 57,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "pinewood": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/los-altos-hills/pinewood-panthers/football/",
    "stateRank": 65,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "woodside-priory": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/portola-valley/priory-panthers/football/",
    "stateRank": 30,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "crystal-springs-uplands": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/hillsborough/crystal-springs-uplands-gryphons/football/",
    "stateRank": 20,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "castilleja": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/palo-alto/castilleja-gators/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "alma-heights-christian": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/pacifica/pacific-bay-christian-eagles/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "pacific-bay-christian": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/pacifica/pacific-bay-christian-eagles/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "summit-tahoma": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/summit-tahoma-tigers/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "summit-rainier": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/summit-rainier-bulldogs/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "mid-peninsula": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/menlo-park/mid-peninsula-dragons/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "design-tech": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/redwood-city/design-tech-dragons/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "luis-valdez-leadership": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/luis-valdez-leadership-academy-lions/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "gilroy": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/gilroy/gilroy-mustangs/football/",
    "stateRank": 871,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "presentation": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/presentation-panthers/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "oakwood": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/morgan-hill/oakwood-hawks/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "trinity-christian": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/monterey/trinity-christian-warriors/football/",
    "stateRank": 60,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "pacific-collegiate": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/santa-cruz/pacific-collegiate-pumas/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "santa-catalina": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/monterey/santa-catalina-cougars/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "eastside-college-prep": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/east-palo-alto/eastside-college-prep-panthers/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "oxford-academy": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/cypress/oxford-academy-patriots/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "mountain-view-academy": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/mountain-view/mountain-view-academy-mustangs/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "st-thomas-more": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/more-knights/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "basis-silicon-valley": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-jose/basis-independent-silicon-valley-bobcats/football/",
    "stateRank": 112,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "stevenson": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/pebble-beach/stevenson-pirates/football/",
    "stateRank": 304,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "york": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/monterey/york-falcons/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "kirby": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/santa-cruz/kirby-prep-griffins/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "lick-wilmerding": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-francisco/lick-wilmerding-tigers/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "urban": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-francisco/urban-blues/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "university": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-francisco/university-red-devils/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "drew": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-francisco/drew-dragons/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "marin-academy": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-rafael/marin-academy-wildcats/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "san-domenico": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/san-anselmo/san-domenico-panthers/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "waldorf": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/mountain-view/waldorf-mavericks/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "cornerstone-christian": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/antioch/cornerstone-christian-cougars/football/",
    "stateRank": 44,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "california-school-for-the-deaf": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/fremont/california-school-for-the-deaf-eagles/football/",
    "stateRank": 102,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "contra-costa-christian": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/walnut-creek/contra-costa-christian-cougars/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "fremont-christian": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/fremont/fremont-christian-warriors/football/",
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "moreau-catholic": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/hayward/moreau-catholic-mariners/football/",
    "stateRank": 429,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "newark-memorial": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/newark/newark-memorial-cougars/football/",
    "stateRank": 846,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "james-logan": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/union-city/james-logan-colts/football/",
    "stateRank": 327,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "american": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/fremont/american-eagles/football/",
    "stateRank": 929,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "irvington": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/fremont/irvington-vikings/football/",
    "stateRank": 629,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  },
  "mission-san-jose": {
    "maxprepsUrl": "https://www.maxpreps.com/ca/fremont/mission-san-jose-warriors/football/",
    "stateRank": 996,
    "lastUpdated": "2026-04-06T04:06:44.110Z"
  }
};
