// This file is auto-generated by scripts/update-maxpreps-teams.mjs
// Source: MaxPreps team pages
// Generated at: 2026-08-24T09:03:32.859Z

export const MAXPREPS_TEAMS_GENERATED_AT = "2026-08-24T09:03:32.859Z";

export type MaxprepsTeamData = {
  maxprepsUrl?: string;
  leagueName?: string;
  schoolMascotUrl?: string;
  stateRank?: number;
  record?: { wins: number; losses: number };
  pointsFor?: number;
  pointsAgainst?: number;
  streak?: string;
  lastUpdated?: string;
};

export const maxprepsTeamData: Record<string, MaxprepsTeamData> = {
  riordan: {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-francisco/archbishop-riordan-crusaders/football/",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  serra: {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-mateo/junipero-serra-padres/football/",
    leagueName: "West Catholic",
    schoolMascotUrl:
      "https://image.maxpreps.io/school-mascot/1/6/e/16e16363-66d8-45af-b777-7820b3256850.gif?version=636559221600000000&width=1024&height=1024",
    stateRank: 26,
    record: {
      wins: 0,
      losses: 0,
    },
    pointsFor: 0,
    pointsAgainst: 0,
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  "st-francis": {
    maxprepsUrl: "https://www.maxpreps.com/ca/mountain-view/saint-francis-lancers/football/",
    leagueName: "West Catholic",
    schoolMascotUrl:
      "https://image.maxpreps.io/school-mascot/d/e/6/de6d3780-e8f6-4a2a-93f2-b5d89499f9b0.gif?version=638773818349606110&width=1024&height=1024",
    stateRank: 68,
    record: {
      wins: 0,
      losses: 0,
    },
    pointsFor: 0,
    pointsAgainst: 0,
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  "st-ignatius": {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-francisco/st-ignatius-wildcats/football/",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  mitty: {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/archbishop-mitty-monarchs/football/",
    leagueName: "West Catholic",
    schoolMascotUrl:
      "https://image.maxpreps.io/school-mascot/0/f/6/0f63870a-34f3-4d5b-9dbf-653c8410f969.gif?version=637116646800000000&width=1024&height=1024",
    stateRank: 72,
    record: {
      wins: 0,
      losses: 0,
    },
    pointsFor: 0,
    pointsAgainst: 0,
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  "valley-christian": {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/valley-christian-warriors/football/",
    leagueName: "West Catholic",
    schoolMascotUrl:
      "https://image.maxpreps.io/school-mascot/8/a/8/8a8c04d2-5606-44cf-9993-34db55474240.gif?version=634618901400000000&width=1024&height=1024",
    stateRank: 109,
    record: {
      wins: 0,
      losses: 0,
    },
    pointsFor: 0,
    pointsAgainst: 0,
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  bellarmine: {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/bellarmine-college-prep-bells/football/",
    leagueName: "West Catholic",
    schoolMascotUrl:
      "https://image.maxpreps.io/school-mascot/0/3/2/032ce3ae-f13d-47f2-ad35-57d995127648.gif?version=635748969600000000&width=1024&height=1024",
    stateRank: 502,
    record: {
      wins: 0,
      losses: 0,
    },
    pointsFor: 0,
    pointsAgainst: 0,
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  "los-gatos": {
    maxprepsUrl: "https://www.maxpreps.com/ca/los-gatos/los-gatos-wildcats/football/",
    leagueName: "Peninsula - Bay",
    schoolMascotUrl:
      "https://image.maxpreps.io/school-mascot/b/d/b/bdb0b593-ef7f-4c69-8c2a-e0a48c934ca7.gif?version=636252687000000000&width=1024&height=1024",
    stateRank: 52,
    record: {
      wins: 0,
      losses: 0,
    },
    pointsFor: 0,
    pointsAgainst: 0,
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  wilcox: {
    maxprepsUrl: "https://www.maxpreps.com/ca/santa-clara/wilcox-chargers/football/",
    leagueName: "Peninsula - Bay",
    schoolMascotUrl:
      "https://image.maxpreps.io/school-mascot/4/1/6/4169ba3d-78d4-48ed-a4a4-2b79af41d3ee.gif?version=636888433200000000&width=1024&height=1024",
    stateRank: 151,
    record: {
      wins: 0,
      losses: 0,
    },
    pointsFor: 0,
    pointsAgainst: 0,
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  "palo-alto": {
    maxprepsUrl: "https://www.maxpreps.com/ca/palo-alto/palo-alto-vikings/football/",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  "menlo-atherton": {
    maxprepsUrl: "https://www.maxpreps.com/ca/atherton/menlo-atherton-bears/football/",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  christopher: {
    maxprepsUrl: "https://www.maxpreps.com/ca/gilroy/christopher-cougars/football/",
    leagueName: "Mount Hamilton",
    schoolMascotUrl:
      "https://image.maxpreps.io/school-mascot/7/7/3/773e862d-e186-44aa-b268-461b4064ce52.gif?version=634347438000000000&width=1024&height=1024",
    stateRank: 310,
    record: {
      wins: 0,
      losses: 0,
    },
    pointsFor: 0,
    pointsAgainst: 0,
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  "oak-grove": {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/oak-grove-eagles/football/",
    leagueName: "Santa Teresa - Foothill",
    schoolMascotUrl:
      "https://image.maxpreps.io/school-mascot/b/5/c/b5c6ef6d-8399-41f6-99b5-2b536ea2b71a.gif?version=638627696580346080&width=1024&height=1024",
    stateRank: 876,
    record: {
      wins: 0,
      losses: 0,
    },
    pointsFor: 0,
    pointsAgainst: 0,
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  livermore: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  granada: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  foothill: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  "amador-valley": {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  "san-ramon-valley": {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  "monte-vista": {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  "mountain-view": {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  "half-moon-bay": {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  "pajaro-valley": {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  harbor: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  watsonville: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  hollister: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  alemany: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  alisal: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  gonzales: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  greenfield: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  "san-benito": {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  sequoia: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  woodside: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  lynbrook: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  soquel: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  "santa-cruz": {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  piedmont: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
  carlmont: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-08-24T09:03:32.859Z",
  },
};
