// Auto-generated by scripts/update-wikipedia-team-logos.mjs
export const wikipediaTeamLogos: Record<string, string> = {
  "riordan": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Dan_White_1977.webp",
  "serra": "https://upload.wikimedia.org/wikipedia/commons/0/07/Engraving_of_Jun%C3%ADpero_Serra_%281787%29_%28cropped%29.jpg",
  "st-francis": "https://upload.wikimedia.org/wikipedia/commons/5/57/Malden_Catholic_Logo.png",
  "st-ignatius": "https://upload.wikimedia.org/wikipedia/commons/2/24/MainBldgFullView.JPG",
  "mitty": "https://upload.wikimedia.org/wikipedia/commons/3/3c/Materdeilogo.png",
  "valley-christian": "https://upload.wikimedia.org/wikipedia/commons/3/3a/Valley_Christian_Schools_Conservatory_Building.JPG",
  "bellarmine": "https://upload.wikimedia.org/wikipedia/commons/5/56/Bellarmine_Block.png",
  "sacred-heart": "https://upload.wikimedia.org/wikipedia/commons/9/9c/St_Chads_Cathedral_1.jpg",
  "los-gatos": "https://upload.wikimedia.org/wikipedia/commons/2/2b/La_Canada_Building.jpg",
  "wilcox": "https://upload.wikimedia.org/wikipedia/commons/b/bd/AdrianWilcoxHighSchoolSantaClaraCalifornia.jpg"
};
