// This file is auto-generated by scripts/update-maxpreps-teams.mjs
// Source: MaxPreps team pages
// Generated at: 2026-05-04T21:20:33.588Z

export const MAXPREPS_TEAMS_GENERATED_AT = "2026-05-04T21:20:33.588Z";

export type MaxprepsTeamData = {
  maxprepsUrl?: string;
  leagueName?: string;
  schoolMascotUrl?: string;
  stateRank?: number;
  record?: { wins: number; losses: number };
  pointsFor?: number;
  pointsAgainst?: number;
  streak?: string;
  lastUpdated?: string;
};

export const maxprepsTeamData: Record<string, MaxprepsTeamData> = {
  riordan: {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-francisco/archbishop-riordan-crusaders/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  serra: {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-mateo/junipero-serra-padres/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "st-francis": {
    maxprepsUrl: "https://www.maxpreps.com/ca/mountain-view/saint-francis-lancers/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "st-ignatius": {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-francisco/st-ignatius-wildcats/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  mitty: {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/archbishop-mitty-monarchs/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "valley-christian": {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/valley-christian-warriors/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  bellarmine: {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/bellarmine-college-prep-bells/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "sacred-heart": {
    maxprepsUrl:
      "https://www.maxpreps.com/local/school/home.aspx?schoolid=1806a4eb-3371-4e7c-a755-835229bc515e/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "los-gatos": {
    maxprepsUrl: "https://www.maxpreps.com/ca/los-gatos/los-gatos-wildcats/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  wilcox: {
    maxprepsUrl: "https://www.maxpreps.com/ca/santa-clara/wilcox-chargers/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "palo-alto": {
    maxprepsUrl: "https://www.maxpreps.com/ca/palo-alto/palo-alto-vikings/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "menlo-atherton": {
    maxprepsUrl: "https://www.maxpreps.com/ca/atherton/menlo-atherton-bears/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  christopher: {
    maxprepsUrl: "https://www.maxpreps.com/ca/gilroy/christopher-cougars/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  leigh: {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/leigh-longhorns/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "oak-grove": {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/oak-grove-eagles/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  salinas: {
    maxprepsUrl: "https://www.maxpreps.com/ca/salinas/salinas-cowboys/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  palma: {
    maxprepsUrl: "https://www.maxpreps.com/ca/salinas/palma-chieftains/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "sacred-heart-prep": {
    maxprepsUrl:
      "https://www.maxpreps.com/local/school/home.aspx?schoolid=27d82a51-2b44-492e-b2cf-114730027de3/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "del-mar": {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/del-mar-dons/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "evergreen-valley": {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/evergreen-valley-cougars/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  independence: {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/independence-76ers/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "james-lick": {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/james-lick-comets/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  lincoln: {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/lincoln-lions/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "live-oak": {
    maxprepsUrl:
      "https://www.maxpreps.com/local/school/home.aspx?schoolid=a52c60ac-fbe9-438f-b052-c1eba43afacd/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "mt-pleasant": {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/mt-pleasant-cardinals/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  overfelt: {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/overfelt-overfelt-royals/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "piedmont-hills": {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/piedmont-hills-pirates/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  pioneer: {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/pioneer-mustangs/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "silver-creek": {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/silver-creek-raiders/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  westmont: {
    maxprepsUrl:
      "https://www.maxpreps.com/local/school/home.aspx?schoolid=1959d651-408f-4764-94a5-144cea89c499/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "willow-glen": {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/willow-glen-rams/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "yerba-buena": {
    maxprepsUrl: "https://www.maxpreps.com/ca/san-jose/yerba-buena-warriors/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  cupertino: {
    maxprepsUrl: "https://www.maxpreps.com/ca/cupertino/cupertino-pioneers/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  fremont: {
    maxprepsUrl: "https://www.maxpreps.com/ca/sunnyvale/fremont-firebirds/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "monta-vista": {
    maxprepsUrl:
      "https://www.maxpreps.com/local/school/home.aspx?schoolid=405614ad-a015-4270-b527-18e899c90824/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "santa-clara-high": {
    maxprepsUrl: "https://www.maxpreps.com/ca/santa-clara/santa-clara-bruins/football/",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  livermore: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  granada: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  foothill: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "amador-valley": {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "san-ramon-valley": {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "monte-vista": {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "mountain-view": {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "half-moon-bay": {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "pajaro-valley": {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  harbor: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  watsonville: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  hollister: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  alemany: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  alisal: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  gonzales: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  greenfield: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "san-benito": {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  sequoia: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  woodside: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  lynbrook: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  soquel: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  "santa-cruz": {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  piedmont: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
  carlmont: {
    maxprepsUrl: "TBD",
    lastUpdated: "2026-05-04T21:20:33.588Z",
  },
};
